version: "3"
services:

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shorterurldb
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - app-network
  mongodb_container:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data_container:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: shorturl
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  mongo_data_container: